name: CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write
  packages: write
  pull-requests: write

jobs:
  notify-pr:
    name: Notificar inicio en PR
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Comentar inicio del pipeline
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'CI/CD en acción. Ejecutando tareas …'
            })

  validate:
    name: Validar servicio mock
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Validar sintaxis Python
        run: python -m py_compile app.py

      - name: Ejecutar pruebas unitarias
        run: python -m unittest discover -s tests -v

      - name: Construir imagen Docker
        run: docker build -t mock-ml-clinico:ci .

  notify-pr-success:
    name: Notificar exito en PR
    if: github.event_name == 'pull_request'
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Comentar finalizacion exitosa del pipeline
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'CI/CD terminado con éxito.'
            })

  publish-image:
    name: Publicar imagen en GitHub Packages
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Iniciar sesion en GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir y publicar imagen Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/jose-milciades/aura-rredict--mlops-u2:latest
            ghcr.io/jose-milciades/aura-rredict--mlops-u2:${{ github.sha }}
